### ISSUE TITLE
Wrong import href in `ep17-theming`

### ISSUE THREAD

**Issue by dominik0711** [Polymer/polycasts#7]
Hi Rob.

First of all thanks for your videos! Great work!
You've got a `typo` (wrong import path) in `ep17-theming` inside `ui-message.html`:

Instead of `<link rel="import" href="../polymer/polymer.html">` it should be `<link rel="import" href="bower_components/polymer/polymer.html">`

**Comment by tomask-de** [comment]
Hi Dominik,

I don't think so. Like Rob described in episode #14 - creating reusable
elements it's supposed to work with polyserve.
So if you run polyserve in the ui-message directory you should end up to
preview the template at localhost:8080/components/ui-message/

best regards
Thomas

2015-06-10 8:34 GMT+02:00 dominik0711 <notifications@github.com>:

**Comment by robrez** [comment]
it's a bit tricky because the workflow for in-production and in-development is different.

In _production_, we expect someone to be reusing our custom element (ui-message.html). They would install our element with `bower install --save ui-message=polycasts/ui-message#master`. In this scenario, ui-message will correctly be placed alongside polymer and any other dependencies in a bower_components directory.  So the relative path, `../polymer/polymer.html`, is correct.

For development, @tomask-de is right, you need to use polyserve or some other DIY method (which can be tedious / a recipe for committing a bad path)

**Comment by robdodson** [comment]
thanks @tomask-de and @robrez for following up, I'm going to close this issue, @dominik0711 I hope it answers your questions? Here's a link to the episode that demonstrates polyserve: https://www.youtube.com/watch?v=p7Q1mQtFGM8&list=PLOU2XLYxmsII5c3Mgw6fNYCzaWrsM3sMN&index=4
